---
title: RoadToBig4
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Big4 Interview Questions - Answers
baseurl: "/roadToBig4"
url: /roadToBig4/
author:
  name: Austin
  url: https://austinph.me
markdown: kramdown
include:
- _pages
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
permalink: "/:year-:month-:day/:title"
paginate: 5
exclude:
- Gemfile
- Gemfile.lock
- tale.gemspec